### ISSUE TITLE
Consider using the rawfile package from uuid-annotator

### ISSUE THREAD

**Issue by robertodauria** [m-lab/switch-monitoring#5]
The `config` package could be replaced by https://github.com/m-lab/uuid-annotator/blob/master/rawfile/provider.go in future, which implements a superset of the features we need.

**Comment by pboothe** [comment]
FYI: When we were talking on VC I thought you were asking about turning the provider test code into a testing module.

You may use the provider code if you like, although in that case I would prefer to migrate it to github.com/m-lab/go and probably change the name.

**Comment by robertodauria** [comment]
switch-monitoring now happily uses `m-lab/go/content` (previously `rawfile`). Closing.
